### ISSUE TITLE
Remove keyboard binding for CMD+D

### ISSUE THREAD

**Issue by ghosh** [hardikjain29/crypto-trading-tracker#1]
Hi,

Firstly thanks for making this. It's useful.

Please consider removing or at least changing the `CMD+D` keyboard binding. Since it is a menubar app, it is overriding the keyboard shortcuts on all other apps.

I'm open to submitting a PR if you want me to remove it or remap it some other key.

Cheers!

**Comment by hardikjain29** [comment]
Hey, 

Glad it's useful.

I am open to PR if you would like to make one.

Thanks! xD
